services:
  app:
    build: .
    container_name: logi-graph
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logi_graph_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    restart: always
    environment:
      POSTGRES_DB: logi_graph_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d logi_graph_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_AUTH: neo4j/123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*,gds.*'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_auth__minimum__password__length: 3
    volumes:
      - neo4j_data:/data
      - ./import:/import
      - ./plugins:/plugins
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7474" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - backend
volumes:
  pg_data:
  neo4j_data:
networks:
  backend: