spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://db:5432/logi_graph_db
        username: postgres
        password: 123
    neo4j:
        uri: bolt://neo4j:7687
        authentication:
            username: neo4j
            password: password
    data:
        redis:
            host: redis
            ports: 6379
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp_use_jdbc_metadata_defaults: false
timefold:
    solver:
        termination:
            spent-limit: 30s