spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:postgresql://db:5432/logi_graph_db
        username: postgres
        password: 123
    neo4j:
        uri: bolt://neo4j:7687
        authentication:
            username: neo4j
            password: 123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect